"""
Amazon Bedrock AgentCore Runtime entry point.
Runs weekly: scrapes deals, analyzes receipts, emails HTML report via SES.
"""

import os
import re

import boto3
import markdown2

from services.analyzer import run_analysis
from services.db import list_receipts, put_price_drops, get_presigned_url
from services.price_scanner import scan_price_drops

NOTIFY_EMAIL = os.environ.get("NOTIFY_EMAIL", "")
REGION = os.environ.get("AWS_DEFAULT_REGION", "us-east-1")

_ses = boto3.client("ses", region_name=REGION)


async def invoke(payload: dict) -> dict:
    """AgentCore Runtime entrypoint — called by EventBridge Scheduler."""
    print(f"[agent] Starting weekly scan. payload={payload}")

    # 1. Refresh all deal sources
    print("[agent] Scraping price drops...")
    drops = scan_price_drops(force_refresh=True)
    count = put_price_drops(drops)
    print(f"[agent] Stored {count} price drop items.")

    # 2. Run AI analysis across all receipts
    print("[agent] Running analysis...")
    markdown_report = run_analysis()

    if not markdown_report.strip():
        print("[agent] No analysis results. Skipping email.")
        return {"status": "no_results"}

    # 3. Replace PDF links with 7-day presigned S3 URLs
    print("[agent] Generating presigned URLs...")
    markdown_report = _presign_links(markdown_report)

    # 4. Convert markdown to HTML and send email
    print("[agent] Sending email report...")
    html = _md_to_html(markdown_report)
    _send_email(html)

    print("[agent] Weekly scan complete.")
    return {"status": "success", "items_found": count}


def _presign_links(markdown: str) -> str:
    """Replace /api/receipt/<id>/pdf links with presigned S3 URLs."""
    receipts_by_id = {r["receipt_id"]: r for r in list_receipts()}

    def replace_link(match: re.Match) -> str:
        receipt_id = match.group(1)
        receipt = receipts_by_id.get(receipt_id)
        if receipt and receipt.get("s3_key"):
            try:
                return get_presigned_url(receipt["s3_key"], expiry=604800)
            except Exception:
                pass
        return match.group(0)

    return re.sub(r"/api/receipt/([^/\s\)\"]+)/pdf", replace_link, markdown)


def _md_to_html(markdown_text: str) -> str:
    """Convert markdown to inline-styled HTML email."""
    body_html = markdown2.markdown(
        markdown_text,
        extras=["tables", "fenced-code-blocks", "break-on-newline"],
    )
    return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body {{ font-family: Arial, sans-serif; max-width: 900px; margin: 0 auto; padding: 20px; color: #333; }}
  h1, h2, h3 {{ color: #005b96; }}
  table {{ border-collapse: collapse; width: 100%; margin: 16px 0; }}
  th {{ background: #005b96; color: white; padding: 10px; text-align: left; }}
  td {{ padding: 8px 10px; border: 1px solid #ddd; }}
  tr:nth-child(even) {{ background: #f5f5f5; }}
  a {{ color: #005b96; }}
  .footer {{ margin-top: 40px; font-size: 12px; color: #999; }}
</style>
</head>
<body>
  <h1>🛒 Costco Weekly Price Match Report</h1>
  {body_html}
  <div class="footer">
    Generated by Costco Purchase Analyzer &mdash; <a href="https://github.com">GitHub</a>
  </div>
</body>
</html>"""


def _send_email(html: str) -> None:
    if not NOTIFY_EMAIL:
        print("[agent] NOTIFY_EMAIL not set — skipping SES send.")
        return
    _ses.send_email(
        Source=NOTIFY_EMAIL,
        Destination={"ToAddresses": [NOTIFY_EMAIL]},
        Message={
            "Subject": {"Data": "🛒 Costco Weekly Price Match Report", "Charset": "UTF-8"},
            "Body": {
                "Html": {"Data": html, "Charset": "UTF-8"},
            },
        },
    )


# ── AgentCore Runtime bootstrap ────────────────────────────────────────────────
if __name__ == "__main__":
    import asyncio
    import uvicorn
    from bedrock_agentcore.runtime import BedrockAgentCoreApp

    bedrock_app = BedrockAgentCoreApp()

    @bedrock_app.entrypoint
    async def handler(payload: dict) -> dict:
        return await invoke(payload)

    uvicorn.run(bedrock_app, host="0.0.0.0", port=8080)
